
networks:
  training_network:
    driver: bridge

services:
  postgres:
    image: postgres
    container_name: postgres_sql_query_tuning_exercise
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - ./scripts/exercise/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - training_network
